### ISSUE TITLE
Select "sacks" in ep_preprocess()

### ISSUE THREAD

**Issue by christianlohr9** [ffverse/ffopportunity#10]
Please select sacks in this function to calculate fantasy points with sacks.

For the ultimate cool stuff include "sack yards" ;)

**Comment by christianlohr9** [comment]
Ok, just found out it's not that trivial.
Because the prediction model needs this `!is.na(air_yards)` filter?

Sack Yards is super easy when getting sacks.
But having sacks would be a game changer...

**Comment by tanho63** [comment]
Yeah, the current model does not compute any sort of expectation on sacks and filters those plays out. If you want to bring sacks back in, I would probably join real play-by-play or player-stats later to add the loss on sacks etc. 

This is a bit outside scope for the moment and unsure when we'll be revisiting the model (busy!).
