### ISSUE TITLE
Jeffery Wilson stats doubled (and maybe others?)

### ISSUE THREAD

**Issue by Jeffery-777** [ffverse/ffopportunity#14]
His numeric stats seem to be doubled and I saw some one else say same thing about Chase Claypool.

**Comment by tanho63** [comment]
Related to roster join here: https://github.com/ffverse/ffopportunity/blob/main/R/ep_preprocess.R#L25

**Comment by JoeSydlowski** [comment]
We think this was an upstream issue with `nflreadr::load_rosters` that has since been resolved

```
expected_points_data <- nflreadr::load_ff_opportunity(seasons = 2022)
expected_points_data |> dplyr::filter(full_name == "Chase Claypool")
expected_points_data |> dplyr::filter(full_name == "Jeffery Wilson")
```

Let us know if you see any other issues pop up!
