### ISSUE TITLE
Bug with the ep_weekly_2022.csv file as of 12/23/2022 `total_fantasy_points` and `total_fantasy_points_exp`

### ISSUE THREAD

**Issue by filpia** [ffverse/ffopportunity#17]
Attaching the file I pulled on the evening of 12/23/2022 from the following [link](https://github.com/ffverse/ffopportunity/releases/download/latest-data/ep_weekly_2022.csv).

[ep_weekly_2022.csv](https://github.com/ffverse/ffopportunity/files/10297770/ep_weekly_2022.csv)

Focusing on Tom Brady to highlight the issue, it looks like the `total_fantasy_points` column is being derived from `rush_fantasy_points` and is ignoring the other point scoring categories `pass_*` and `rec_*`

<img width="725" alt="image" src="https://user-images.githubusercontent.com/10145677/209416032-41972706-b6d6-4228-ac30-b28b7c2b5fd2.png">

Will see if I can ID the issue in the code but in the mean time I thought I'd raise the alarm in the mean time

**Comment by filpia** [comment]
I think I've identified the issue and it only affects QBs. Notice in #15 by @JoeSydlowski  these [lines](https://github.com/ffverse/ffopportunity/blob/6b98da50973047f579d63db717c7a59189c33977/R/ep_summarize.R#L151-L152) were changed and now only sum receiving and rushing points whereas before you were using `total_fantasy_points = sum(dplyr::across(tidyselect::ends_with("fantasy_points"), sum))`. The old code also included `pass_fantasy_points` in the sum, thus QBs are mainly affected by this bug

**Comment by filpia** [comment]
I'm not able to open a PR but I have the code locally if you'd like to give me permission to contribute to the project. If not, that's cool. Here's the lines I changed in `R/ep_summarize.R`

```r

dplyr::mutate(
      total_yards_gained = .data$rec_yards_gained + .data$rush_yards_gained + .data$pass_yards_gained,
      total_yards_gained_exp = .data$rec_yards_gained_exp + .data$rush_yards_gained_exp + .data$pass_yards_gained_exp,
      total_touchdown = .data$rec_touchdown + .data$rush_touchdown + .data$pass_touchdown,
      total_touchdown_exp = .data$rec_touchdown_exp + .data$rush_touchdown_exp + .data$pass_touchdown_exp,
      total_first_down = .data$rec_first_down + .data$rush_first_down + .data$pass_first_down,
      total_first_down_exp = .data$rec_first_down_exp + .data$rush_first_down_exp + .data$pass_first_down_exp,
      total_fantasy_points = .data$rec_fantasy_points + .data$rush_fantasy_points + .data$pass_fantasy_points,
      total_fantasy_points_exp = .data$rec_fantasy_points_exp + .data$rush_fantasy_points_exp + .data$pass_fantasy_points) %>%
    dplyr::ungroup() %>%
```

**Comment by tanho63** [comment]
Good catch! If you'd like to make a PR we'd be happy to review it :)

**Comment by filpia** [comment]
@tanho63 can you give me publish access on the repo? I think I need it in order to open a PR

**Comment by tanho63** [comment]
You should be able to propose changes by making a fork, making changes to a new branch there, and then making a PR from that branch back to this repository

**Comment by filpia** [comment]
Opened #18

**Comment by JoeSydlowski** [comment]
Thanks for the PR @filpia!
I originally changed this part because it was double counting passing and receiving yards under total_yards_gained_team* fields. You were right to add passing back in at the player level and I excluded the double counting from the team level like I should have to begin with.

Always appreciate an extra set of eyes on this stuff!
